<a href="https://colab.research.google.com/github/mradi004/data_science/blob/main/Numpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [4]:
arr=np.array(l)

In [6]:
arr1=np.array([[1,2],[3,4]])

In [7]:
arr1

array([[1, 2],
       [3, 4]])

In [8]:
a=[1,2,3,4,5]

In [9]:
n1=np.array(a)

In [10]:
n2=np.asarray(a)

In [12]:
n3=np.asanyarray(a)

In [13]:
b=np.matrix([[1,2,3],[4,5,6]])

In [14]:
b2=np.asarray(b)

In [15]:
b3=np.asanyarray(b)

In [16]:
type(b)
type(b2)
type(b3)

numpy.matrix

In [17]:
type(b3)

numpy.matrix

In [18]:
type(b2)

numpy.ndarray

In [19]:
type(b)

numpy.matrix

In [20]:
adi=np.array([1,2,3,4,5])

In [21]:
c=adi

In [22]:
c[0]=200

In [23]:
adi

array([200,   2,   3,   4,   5])

In [24]:
d=np.copy(a)

In [25]:
d

array([1, 2, 3, 4, 5])

In [26]:
a

[1, 2, 3, 4, 5]

In [27]:
a[0]=12

In [28]:
d

array([1, 2, 3, 4, 5])

In [29]:
a

[12, 2, 3, 4, 5]

In [30]:
d

array([1, 2, 3, 4, 5])

In [ ]:
#functions of numpy

In [32]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [34]:
iterable=(i*i for i in range(5))

In [35]:
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [43]:
kashyap=np.fromstring('23 45 65 78 99 3',float,sep=' ')

In [44]:
kashyap

array([23., 45., 65., 78., 99.,  3.])

In [45]:
#numpy datatypes

In [46]:
l=[2,3,4,5,6]

In [47]:
ar=np.array(l)

In [48]:
ar

array([2, 3, 4, 5, 6])

In [49]:
ar.ndim

1

In [50]:
ar2=np.array([[1,2,3,4],[3,4,5,6]])

In [51]:
ar2.ndim

2

In [52]:
ar.shape

(5,)

In [54]:
ar2.shape

(2, 4)

In [55]:
ar22=np.array([(1,2,3,4,5),(3,5,6.7,8,7)])

In [56]:
ar22

array([[1. , 2. , 3. , 4. , 5. ],
       [3. , 5. , 6.7, 8. , 7. ]])

In [57]:
range(5)

range(0, 5)

In [58]:
list(range(5))


[0, 1, 2, 3, 4]

In [59]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [60]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [62]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [63]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
on=np.ones((2,3))

In [69]:
on*7

array([[7., 7., 7.],
       [7., 7., 7.]])

In [72]:
np.logspace(2,7,100,base=2)

array([  4.        ,   4.14250963,   4.2900965 ,   4.44294152,
         4.601232  ,   4.76516197,   4.93493233,   5.11075118,
         5.29283399,   5.48140394,   5.67669215,   5.87893797,
         6.08838928,   6.30530281,   6.5299444 ,   6.76258938,
         7.00352291,   7.25304027,   7.51144729,   7.77906067,
         8.05620844,   8.34323025,   8.64047791,   8.94831573,
         9.26712102,   9.59728451,   9.93921087,  10.29331918,
        10.66004346,  11.03983316,  11.43315379,  11.84048741,
        12.26233328,  12.69920842,  13.15164828,  13.62020741,
        14.10546008,  14.60800105,  15.12844624,  15.66743356,
        16.22562359,  16.80370048,  17.40237276,  18.02237417,
        18.66446463,  19.32943111,  20.01808862,  20.73128121,
        21.469883  ,  22.23479926,  23.0269675 ,  23.84735864,
        24.6969782 ,  25.57686749,  26.48810496,  27.43180745,
        28.40913162,  29.42127531,  30.46947906,  31.55502759,
        32.6792514 ,  33.84352839,  35.04928555,  36.29

In [ ]:
#random function

In [75]:
akm=np.random.randn(3,4)

In [77]:
import pandas as pd
pd.DataFrame(akm ,index=["Adi","sat","bhutki"])

0         1         2         3
Adi    -0.746969 -0.123877  0.533991  0.794941
sat    -0.080170  0.591585 -0.103845 -0.426424
bhutki -1.016656 -1.316648 -0.253131 -1.202126

In [79]:
aditya=np.random.randint(1,100,(4,4))

In [81]:
aditya1=aditya.reshape(8,2)

In [82]:
aditya1[1][1]

np.int64(6)

In [83]:
aditya1

array([[82,  7],
       [55,  6],
       [64, 68],
       [91, 21],
       [88, 37],
       [84, 56],
       [12, 55],
       [ 8, 51]])

In [3]:
import numpy as np

arr=np.random.randint(1,100,(5,5))

In [4]:
arr>50

array([[False, False,  True,  True,  True],
       [False, False,  True, False,  True],
       [ True, False,  True, False, False],
       [ True,  True, False,  True,  True],
       [False,  True,  True,  True, False]])

In [5]:
arr[2:4,[1,2]]

array([[49, 59],
       [61, 10]])

In [ ]:
#inbuilt mathematical function

In [6]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [7]:
arr1+arr2

array([[4, 4, 3],
       [3, 3, 4],
       [4, 3, 2]])

In [8]:
arr1@arr2

array([[10, 10,  9],
       [ 8,  8,  6],
       [ 8,  8,  7]])

Broadcasting

In [10]:
arr3=np.zeros((4,4))

In [11]:
arr4=np.array([1,2,3,4])

In [12]:
arr3+arr4

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [13]:
arr5=np.random.randint(1,4,(3,4))

In [14]:
np.sqrt(arr5)

array([[1.41421356, 1.        , 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.73205081, 1.73205081, 1.        ]])

#lecture 2nd

In [ ]:
#Numpy---Array Manipulation

In [15]:
import numpy as np

In [16]:
arr=np.random.randint(1,10,(3,4))

In [17]:
arr.reshape(2,6)

array([[7, 4, 9, 9, 7, 9],
       [6, 9, 5, 2, 8, 1]])

In [18]:
arr.T

array([[7, 7, 5],
       [4, 9, 2],
       [9, 6, 8],
       [9, 9, 1]])

In [20]:
arr.flatten()

array([7, 4, 9, 9, 7, 9, 6, 9, 5, 2, 8, 1])

In [21]:
arr

array([[7, 4, 9, 9],
       [7, 9, 6, 9],
       [5, 2, 8, 1]])

In [22]:
np.squeeze(arr)

array([[7, 4, 9, 9],
       [7, 9, 6, 9],
       [5, 2, 8, 1]])

In [23]:
data=np.array([[1],[2],[3]])

In [24]:
np.squeeze(data)

array([1, 2, 3])

In [26]:
np.roll(data,1)

array([[3],
       [1],
       [2]])

In [ ]:
#binary operations

In [27]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))


In [28]:
arr1+arr2

array([[14, 10, 11, 10],
       [12,  5,  9, 13],
       [12,  7, 10,  7]])

In [29]:
arr1-arr2

array([[ 2, -2,  1,  4],
       [-6, -3,  5, -3],
       [ 2,  3,  4,  5]])

In [30]:
arr1*arr2

array([[48, 24, 30, 21],
       [27,  4, 14, 40],
       [35, 10, 21,  6]])

In [31]:
arr1%arr2

array([[2, 4, 1, 1],
       [3, 1, 1, 5],
       [2, 1, 1, 0]])

In [32]:
arr1**arr2

array([[262144,   4096,   7776,    343],
       [ 19683,      1,     49, 390625],
       [ 16807,     25,    343,      6]])

In [33]:
arr1&arr2

array([[0, 4, 4, 3],
       [1, 0, 2, 0],
       [5, 0, 3, 0]])

In [34]:
arr1>arr2

array([[ True, False,  True,  True],
       [False, False,  True, False],
       [ True,  True,  True,  True]])

String function

In [37]:
ar=np.array(['aditya','kumar'])

In [38]:
np.char.upper(ar)

array(['ADITYA', 'KUMAR'], dtype='<U6')

In [39]:
np.char.title(ar)

array(['Aditya', 'Kumar'], dtype='<U6')

In [40]:
np.char.capitalize(ar)

array(['Aditya', 'Kumar'], dtype='<U6')

Numerical function

In [41]:
arr1

array([[8, 4, 6, 7],
       [3, 1, 7, 5],
       [7, 5, 7, 6]])

In [42]:
np.sin(arr1)

array([[ 0.98935825, -0.7568025 , -0.2794155 ,  0.6569866 ],
       [ 0.14112001,  0.84147098,  0.6569866 , -0.95892427],
       [ 0.6569866 , -0.95892427,  0.6569866 , -0.2794155 ]])

In [43]:
np.cos(arr1)

array([[-0.14550003, -0.65364362,  0.96017029,  0.75390225],
       [-0.9899925 ,  0.54030231,  0.75390225,  0.28366219],
       [ 0.75390225,  0.28366219,  0.75390225,  0.96017029]])

#Numpy 3rd lecture

In [ ]:
#sort,search and counting functions

In [44]:
arr=np.array([1,2,3,4])

In [45]:
np.sort(arr)

array([1, 2, 3, 4])

In [46]:
np.searchsorted(arr,89)

np.int64(4)

In [48]:
arr1=np.array([0,4,5,6,2,3,8,75,6,7])

In [49]:
np.count_nonzero(arr1)

9

In [51]:
np.where(arr1>5)

(array([3, 6, 7, 8, 9]),)

In [53]:
np.extract(arr1>6,arr1)

array([ 8, 75,  7])

In [54]:
arr1

array([ 0,  4,  5,  6,  2,  3,  8, 75,  6,  7])

In [ ]:
#byte-swapping

In [55]:
arr1.byteswap()

array([                  0,  288230376151711744,  360287970189639680,
        432345564227567616,  144115188075855872,  216172782113783808,
        576460752303423488, 5404319552844595200,  432345564227567616,
        504403158265495552])

In [ ]:
#numpy-----matrix library

In [56]:
import numpy.matlib as nm

In [59]:
nm.zeros((5,4))

matrix([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#linear algebra

In [60]:
arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))

In [61]:
np.dot(arr1,arr2)

array([[ 30,  38,  15],
       [ 45,  59,  21],
       [ 99, 125,  48]])